 <?php

 $title = 'Edit route';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'route',
     array(	
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formHidden($form->get('user_id')->setAttribute('value',$this->userid));
 echo "<div class='form-group'>";
 echo $this->formRow($form->get('route_name')->setAttribute('class','form-control'));
 echo "</div>";
 echo "<div class='form-group'>";
 echo $this->formRow($form->get('origin')->setAttribute('class','form-control'));
 echo "</div>";
 echo "<div class='form-group'>";
 echo $this->formRow($form->get('destination')->setAttribute('class','form-control'));
 echo "</div>";
 echo "<div class='form-group'>"; 
 echo $this->formRow($form->get('travel_mode')->setAttribute('class','form-control'));
 echo "</div>"; 
 echo $this->formSubmit($form->get('submit')->setAttribute('class','btn btn-default'));
 echo $this->form()->closeTag();