 <?php
 // module/Album/view/mapit/mapit/delete.phtml:

 $title = 'Delete location';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Are you sure that you want to delete
     '<?php echo $this->escapeHtml($mapit->mapit_type); ?>' by
     '<?php echo $this->escapeHtml($mapit->mapit_name); ?>'?
 </p>
 <?php
 $url = $this->url('mapit', array(
     'action' => 'delete',
     'id'     => $this->id,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $mapit->id; ?>" />
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>