 <?php
 $windowTitle = $displayname;
 $this->headTitle('Welcome');
 $this->headLink()->appendStylesheet('/css/dashboard/default.css');
 $this->headScript()->appendFile( '/js/Chart.js/Chart.js', 'text/javascript' );
 $this->headScript()->appendFile( '/js/dashboard/default.js', 'text/javascript' );
 ?>

                   <h2 class="sub-header"><?php echo $displayname; ?></h2>
                   <div class="row" id="chart-container">
                       <canvas id="myChart" width="800" height="350"></canvas>
                   </div>    
                   