 <?php
 $user_type = 'My users';
 $this->headTitle($user_type);
 ?>
 <h1><?php echo $this->escapeHtml($user_type); ?></h1>
 <p>
     <a href="<?php echo $this->url('user', array('action'=>'add'));?>">Add new user</a>
 </p>

 <table class="table">
 <tr>
     <th>Email</th>
     <th>Password</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($users as $user) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($user->email);?></td>
     <td><?php echo $this->escapeHtml($user->password);?></td>
     <td>
         <a href="<?php echo $this->url('user',
             array('action'=>'edit', 'id' => $user->id));?>">Edit</a>
         <a href="<?php echo $this->url('user',
             array('action'=>'delete', 'id' => $user->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>