/* DB SETUP FOR ADMIN AREA */
--/------------------------------------------+	CREATE TABLES
--/ Add indexes to tables with large sets of data.
CREATE TABLE APPLICATION
(
	APPLICATION_ID NUMBER NOT NULL
	,APPLICATION_NAME VARCHAR2(50) NOT NULL
	,CREATED_ON DATE
	,CREATED_BY VARCHAR2(20)
	,UPDATED_ON DATE NOT NULL
	,UPDATED_BY VARCHAR2(20) NOT NULL
);

CREATE TABLE PROJECT
(
	PROJECT_ID NUMBER NOT NULL
	,PROJECT_NAME VARCHAR2(50) NOT NULL
	,PROJECT_DESCRIPTION VARCHAR2(500 CHAR)
	,CREATED_ON DATE
	,CREATED_BY VARCHAR2(20)
	,UPDATED_ON DATE NOT NULL
	,UPDATED_BY VARCHAR2(20) NOT NULL
);

CREATE TABLE AUTH_USER
(
	AUTH_USER_ID NUMBER NOT NULL
	,USER_NAME VARCHAR2(50) NOT NULL
	,HASHED_PASSWORD VARCHAR2(500 CHAR)
	,EMAIL VARCHAR2(50) NOT NULL
	,CREATED_ON DATE
	,CREATED_BY VARCHAR2(20)
	,UPDATED_ON DATE NOT NULL
);

CREATE TABLE TEMP_USER
(
	TEMP_USER_ID NUMBER NOT NULL
	,USER_NAME VARCHAR2(50) NOT NULL
	,HASHED_PASSWORD VARCHAR2(500 CHAR)
	,CREATED_ON DATE
	,CREATED_BY VARCHAR2(20)
	,UPDATED_ON DATE NOT NULL
);

CREATE TABLE ROVER
(
	ROVER_ID NUMBER NOT NULL
	,ROVER_NAME VARCHAR2(50) NOT NULL
	,CREATED_ON DATE
	,CREATED_BY VARCHAR2(20)
	,UPDATED_ON DATE NOT NULL
	,UPDATED_BY VARCHAR2(20) NOT NULL
);


--/------------------------------------------+	CREATE VIEWS
--/ Each of these views should represent a generated report.

--/------------------------------------------+	CREATE FUNCTIONS
--Format all phone numbers, emails and dates using regexp.

--/EMAIL FUNCTONS
--email result from funciton

--/------------------------------------------+	CREATE SEQUENCES
CREATE OR REPLACE SEQUENCE APPLICATION_SEQ
	START WITH 1
	INCREMENT BY 1
	CACHE 20
	NOORDER;

	
--/------------------------------------------+	TABLE INSERTS
/*
INSERT INTO APPLICATIONS
VALUES (
	APLICATION_SEQ.NEXTVAL
	,''
	,''
	,''
	,''
	,''
);
*/