 <?php
 $title = 'Add new project';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('project', array('action' => 'add')));
 $form->prepare();

//  echo $this->form()->openTag($form);
//  echo $this->formHidden($form->get('id'));
//  echo $this->formRow($form->get('project_type'));
//  echo $this->formRow($form->get('project_name'));
//  echo $this->formSubmit($form->get('submit'));
//  echo $this->form()->closeTag();
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();