 <?php
 $project_type = 'My projects';
 $this->headTitle($project_type);
 ?>
 <h1><?php echo $this->escapeHtml($project_type); ?></h1>
 <p>
     <a href="<?php echo $this->url('project', array('action'=>'add'));?>">Add new project</a>
 </p>

<table class="table table-striped">
<tr>
     <th>Project Type</th>
     <th>Project Name</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($projects as $project) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($project->project_type);?></td>
     <td><?php echo $this->escapeHtml($project->project_name);?></td>
     <td>
         <a href="<?php echo $this->url('project',
             array('action'=>'edit', 'id' => $project->id));?>">Edit</a>
         <a href="<?php echo $this->url('project',
             array('action'=>'delete', 'id' => $project->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>