<?php

function regex_filter($string)
{
    $output="";
    
    #mixed preg_replace ( mixed $pattern , mixed $replacement , mixed $subject [, int $limit = -1 [, int &$count ]] )
    //$pattern = '/(\w+) (\d+), (\d+)/i';
    //$replacement = '${1}1,$3';
    
    $pattern = '/#request_data+/i';
    $replacement = 'isset(#request_data';
    #$output = preg_replace($pattern, $replacement, $string);    
    $output = preg_replace($pattern, $replacement, $string);
    return $output;
}


//echo regex_filter('April 15, 2003');
//echo regex_filter("#request_data['catalog_description']");