<?php require_once('snippets/header.php'); ?>

        <div data-role="page" id="about" title="<?php echo $title; ?>">   
            <div data-role="header" data-position="fixed" data-theme="b">
                <h1><?php echo $title; ?></h1>
            </div><!-- /header -->    
            <div data-role="content">
                <p class="smaller">This tool was developed for the Springer API Challenge 2.0. The main goal was to develop an application that provides a novel search solution based on an analysis of trends in the metadata.</p>    
            </div><!-- /content -->
        </div>    
<?php require_once('snippets/footer.php'); ?> 