<?php include('snippets/header.php'); ?>

    <div data-role="page" data-dom-cache="false" id="home" title="<?php echo $title; ?>" data-theme="a">
    	
        <div data-role="header" data-position="fixed">
        <a data-rel="back" data-transition="slide">Back</a>
            <h1><?php echo $title; ?></h1>        
        </div><!-- /header -->
    
        <div data-role="content">	
			<h2>Current search monthly trends</h2>
            <div id="chartdiv" style="width: 100%; height: 400px;"></div>
            <?php echo $related_images; ?>

        </div><!-- /content -->
    
<?php require_once('snippets/footer.php'); ?>  