<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="description" content="">
        <meta name="author" content=""> 
		<?php 
		if (isset($_SERVER['HTTP_USER_AGENT']) &&
		(strpos($_SERVER['HTTP_USER_AGENT'], 'MSIE') !== false))
			header('X-UA-Compatible: IE=edge,chrome=1');
		?>        
        
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ?>
	    <?php echo $this->headTitle($this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php /* Styles */?>
        <?php $curr_css = isset($_SESSION['auth_user'])?'css/dashboard.css':'css/signin.css'; ?>
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))                        
        				->prependStylesheet($this->basePath() . $curr_css)
        				->prependStylesheet($this->basePath() . '/css/default.css')
        				->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        				->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css') ; ?>        
        <?php /* Scripts */?>
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
        
    </head>
    <body>             
<?php if (isset($_SESSION['auth_user'])) { ?>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Project name</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Settings</a></li>
            <li><a href="#">Profile</a></li>
            <li><a href="#">Help</a></li>
            <li><a href="/user/signout">Logout</a></li>
          </ul>
          <form action="/search" method="post" class="navbar-form navbar-right">
            <input id="q" type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
      </div>
    </div>

<?php $current_page = ""; ?>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
        <?php echo $this->navigation('navigation')
		    ->menu()
		    ->setMinDepth(0)
		    ->setMaxDepth(0)
		    ->setUlClass('nav nav-sidebar')
		    ->render();
		?>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        	<?php echo $this->navigation('navigation') // <-- Update this!!
			    ->breadcrumbs()
			    ->setMinDepth(0)
			    ->setPartial(array('partial/breadcrumb.phtml', 'Album'));
			?>
			<?php echo $this->content; ?>
        </div>
      </div>
    </div>
	<?php } else { echo "<div class=\"container\">" .$this->content."</div><!-- /container -->";  } ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>