<?php 
$show_modal = isset($_SESSION['login_message'])?true:false;
$li_option =  ( isset($_SESSION['auth_user']) && isset($_SESSION['auth_user']['email']) ) ? 
                    "<a href='user/signout'>Sign Out</a>" : 
                    "<button id=\"btn_signin\" class=\"btn btn-primary\" data-toggle=\"modal\" data-target=\".bs-example-modal-sm\">Sign In</button>";
?>
<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="description" content="">
        <meta name="author" content=""><?php 
        if (isset($_SERVER['HTTP_USER_AGENT']) &&
        (strpos($_SERVER['HTTP_USER_AGENT'], 'MSIE') !== false))
            header('X-UA-Compatible: IE=edge,chrome=1'); ?>             
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') . " \n "; ?>
       <?php echo $this->headTitle($this->translate('AdaptedPro'))->setSeparator(' - ')->setAutoEscape(false) . " \n "; ?>
       <?php $curr_css = isset($_SESSION['auth_user'])?'css/bootstrap/dashboard.css':'/css/bootstrap/cover.css'; ?>
<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico')) 
                        ->prependStylesheet($this->basePath() . $curr_css)
                        ->prependStylesheet($this->basePath() . '/css/site/default.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap/sticky-footer-navbar.css')
        ; ?>
        <link href='http://fonts.googleapis.com/css?family=Dosis:300,400' rel='stylesheet' type='text/css'>
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/docs.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',)); ?>
        
    </head>
    <body<?php if (!isset($_SESSION['auth_user'])) { echo ' class="splash"';} ?>>            
<?php if (isset($_SESSION['auth_user'])) { ?>
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                      </button>
                      <a class="navbar-brand logo" href="/" title=""></a>
                </div>
                <div class="navbar-collapse collapse">
                      <ul class="nav navbar-nav navbar-right">
                        <li><a href="#"><span class="glyphicon glyphicon-cog"></span></a></li>
                        <li><a href="#"><span class="glyphicon glyphicon-inbox"></span></a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">View Profile</a></li>
                                <li><a href="#">Edit Profile</a></li>
                                <li><a href="/user/signout">Logout</a></li>
                              </ul>
                        </li>
                        <li><a href="#"><span class="glyphicon glyphicon-question-sign"></span></a></li>            
                      </ul>
                     <form action="/search" method="post" class="navbar-form navbar-right">
                        <input id="q" type="text" class="form-control" placeholder="Search&hellip;">
                      </form>
                </div>
            </div>
        </div>        
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-3 col-md-2 sidebar">
                <?php echo $this->navigation('navigation')
                    ->menu()
                    ->setMinDepth(0)
                    ->setMaxDepth(0)
                    ->setUlClass('nav nav-sidebar')
                    ->render();
                ?>
                </div>
              </div>      
              <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
<?php echo $this->content; ?>        
              </div>      
        </div>
    <?php } else { ?>
        <div id="fb-root"></div>
        <script type="text/javascript">
            window.fbAsyncInit = function() {
                  FB.init({ appId : '200668723295785', status : true, cookie : true, xfbml : true });
                  FB.Event.subscribe('auth.authResponseChange', function(response) {
                    if (response.status === 'connected') {
                      getFBUser(1);
                    } else if (response.status === 'not_authorized') {
                        getFBUser(2);
                    } else {
                        getFBUser(2);
                    }
                  });
            };
    
            (function(d){
                var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
                if (d.getElementById(id)) {return;}
                js = d.createElement('script'); js.id = id; js.async = true;
                js.src = "//connect.facebook.net/en_US/all.js";
                ref.parentNode.insertBefore(js, ref);
            }(document));

            function getFBUser(x) {
                if (x==1) {
                    FB.api('/me', function(response) {
                        user_logged_in(response);
                    });
                } else if(x==2) {
                    FB.login(function(response) {
                        if (response.authResponse) {                            
                            FB.api('/me', function(response) {
                                if (response.verified == true) {
                                    user_logged_in(response);
                                }
                            });                    
                        }                        
                    }, {scope: 'email,user_likes,create_event,user_birthday'});                
                } 
            }

            function user_logged_in(resp) {
                $.post('/user/facebook',resp,function(msg) {
                	if (msg['reply']) {
                        window.location.replace("/");
                    }
                });
            }              
        </script>
        <div class="site-wrapper">
            <div class="site-wrapper-inner">
                <div class="cover-container">                
<?php echo $this->content; ?>                    
                </div>
            </div>
        </div>
        <div id="footer">
            <div class="container">
                <p class="text-muted"><small>&copy; <?php echo date('Y'); ?> AdaptedPro - All Rights Reserved.</small>&nbsp;|&nbsp;<small><a href='#'>About</a></small>&nbsp;|&nbsp;<small><a href='#'>Privacy &amp; Terms</a></small></p>
            </div>
        </div>
        <div id="login_modal" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-sm">
                <div class="modal-content">                             
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title" id="myModalLabel">Please sign in</h4>
                    </div>
                    <form id="login_form" role="form" action="user/signin" method="post">
                        <div class="modal-body">                        
                            <div class="form-group">
                                <div class="fb-login-button" data-max-rows="1" data-size="large" data-show-faces="false" data-auto-logout-link="true"></div>
                            </div>                   
                            <?php echo (isset($_SESSION['login_message'])?'<p class="red">'.$_SESSION['login_message'].'</p>':''); ?>
                            <?php if( isset($_SESSION['login_message']) ) unset($_SESSION['login_message']); ?>
                            
                            <div class="form-group">
                                <input type="email" name="email" class="form-control" placeholder="Email address" required autofocus>
                            </div>
                            <div class="form-group">
                                <input type="password" name="password" class="form-control" placeholder="Password" required>
                            </div>
                            <div class="checkbox">    
                                <label class="checkbox"> Remember me</label> <input type="checkbox" value="remember-me">
                            </div>                        
                      </div>              
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button class="btn btn-primary" name="go" type="submit">Sign in</button>
                      </div>
                    </form>                 
                </div>
            </div>
        </div><?php }         
    if (count($this->inlineScript()) > 0) echo $this->inlineScript(); 
    if ($show_modal == true) echo "\n <script> $(function() {  $('#btn_signin').trigger( 'click' ); }); </script>"; ?>    
    </body>
</html>