<?php echo $this->doctype(); ?>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
		<?php 
		if (isset($_SERVER['HTTP_USER_AGENT']) && (strpos($_SERVER['HTTP_USER_AGENT'], 'MSIE') !== false))
			header('X-UA-Compatible: IE=edge,chrome=1');
		?>             
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ?>
        
	    <?php echo $this->headTitle($this->translate('Utatis'))->setSeparator(' - ')->setAutoEscape(false) ?>
        	    
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico')) 
        				->prependStylesheet($this->basePath() . '/css/carousel.css')
        				->prependStylesheet($this->basePath() . '/css/default.css')
        				->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        				->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ; ?>           

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
  
  
        <?php echo $this->navigation('navigation')
		    ->menu()
		    ->setMinDepth(0)
		    ->setMaxDepth(0)
		    ->setUlClass('nav nav-sidebar')
		    ->render();
		?>  

<?php //echo $this->content; ?>

    <?php 
    /*-- Bootstrap core JavaScript */
    echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/docs.min.js')
            ->prependFile($this->basepath() . '/js/ie10-viewport-bug-workaround.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/jquery.min.js')
        ; ?>       
  </body>
</html>
