 <?php
 // module/Album/view/user/user/delete.phtml:

 $title = 'Delete upload';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Are you sure that you want to delete? </p>
 <?php
 $form->setAttribute('action', $this->url('upload', array('action' => 'delete')));
 $form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();

?>