      <form id="login_form" class="form-signin" role="form" action="user/signin">
        <h2 class="form-signin-heading">Please sign in</h2>
        <input name="user_email" type="email" class="form-control" placeholder="Email address" required autofocus>
        <input name="user_password" type="password" class="form-control" placeholder="Password" required>
        <label class="checkbox">
          <input name="remember" type="checkbox" value="remember-me"> Remember me
        </label>
        <button id="submit" class="btn btn-lg btn-primary btn-block" name="go" type="submit">Sign in</button>
      </form>
	 <!-- 
      <form id="signup_form" class="form-signin" role="form" action="user/signup">
        <h2 class="form-signin-heading">New to AGC? Sign up</h2>
        <input name="new_user_email" type="email" class="form-control" placeholder="Email address" required autofocus>
        <input name="new_user_password" type="password" class="form-control" placeholder="Password" required>
        <button id="submit" class="btn btn-lg btn-primary btn-block" name="go" type="submit">Sign Up for AGC</button>        
      </form>
      -->
      
<style>
<!--
#signup-form {
}
-->
</style>
      
<script type="text/javascript">
<!--
$(function() {
	/*
	$('#login_form').submit(function () {
		return false;
	});

	$('#submit').click(function() {
		$.ajax({
			type:'POST',
			url:'user/signin'
		});
	});

	function ajax_call()
	{
		$.ajax({
			type'POST',
			url:'/user/signin',
			//data:$('.form_control').serialize(),
			success:function(m) {
				console.log('Hello World!!!!');
			}
		});
	}
	*/
});
//-->
</script>	