	            <div class="inner cover">	            
	            <!-- 
	            <iframe id="vid_player" width="560" height="420" src="//www.youtube.com/embed/QJfNZp8nqBk" frameborder="0" allowfullscreen></iframe>
	                <h1 class="cover-heading">Playtime is Here</h1>
	                <p class="lead">Get inspired or inspire others!<br> <a href="#" class="btn btn-lg btn-default">Let me in</a></p>
	            -->
	            
	            
<?php var_dump($_SESSION); ?>	            
	            </div>